language: java
branches:
  only:
  - dev
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
- openjdk7
- oraclejdk7
env:
  global:
  - secure: CkTpaU75H56w7/9FKhVPOfFe7SRdmnKNe2IrMTDhOwoVA52gPDhX5Z8K2Aql01QF/FtciqAW3ZtzjMUqQWBQmYSaIf47JuRIs2pHFvb+hBVkc1WjNiKzyR8JZQXv73kYiAKoauYhaQBRGWVo+VP1W7tr1w4q7oWpQqhFRnkE4wQ=
  - secure: fxwa1xU9OF+0JRkX8jovLMDM+4Wm0Yz1uLAgwZ5jJ7JUm9kw7VnLvguECtBs/gSgpeTnXFd6Sfk2Er9MdinXfNRyrA0aetx3VEHBXB7CzX7YXdCRj1OrBv/XpR2FtAHXSnFYaSS7K03nZFwZq/upUmCrIQCsxrCn6SYXgmHkM8k=
  - secure: ApirEqwtUB+uE4fP9Qwa2iJ4XEtmw3eH7WlBa3OlAsTQ9+GfJGXKhW0IMByHyXtCeKWN+6zdZZP+Kb0Y1yA87dU5fUFmeUkvbQVFs5NyC9e8cJpea2htxH6HhypNm01xhZ5I8X/BZxj0bZfwhkQVjaVnElJfoR9wv6gWgj33QPQ=
  - secure: EsFVFprXwBscOnDCyi5ACKljkQIirBy2QXoSRGX4hGsdm6AfWY5vgyPghs7qQsGMHR1Uya+eyAjrM/ICZoXrJbkZh+dr75Qrp4UNWN/904WbenA8xfQkyHBXnnW00KHcE6sx33glpYy/iR6HJBBrZqkLqmP361w05PEy0UjucJ0=
